# pull official base image
FROM python:3.8.0


# set work directory
WORKDIR /usr/src/app

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .

RUN python manage.py makemigrations
# RUN python manage.py migrate
RUN python manage.py collectstatic --noinput

#EXPOSE 8000
#EXPOSE 8001

#CMD ["daphne", "-p", "8000", "crypto_ext_backend.asgi:application"]