# Generated by Django 3.2.12 on 2022-02-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('error_from', models.TextField(blank=True, null=True)),
                ('error_type', models.CharField(choices=[('DB', 'DB_ERROR'), ('FE', 'Fetch error'), ('TR', 'TOO Many requests'), ('UN', 'UNKNOWN error')], default='UN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
