# Generated by Django 3.2.12 on 2022-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_gainer_losser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCryptoGainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_img', models.CharField(max_length=500)),
                ('coin_name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=500)),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('percentage_change', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopCryptoLoser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_img', models.CharField(max_length=500)),
                ('coin_name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=500)),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('percentage_change', models.FloatField()),
            ],
        ),
    ]
